ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "homeCity" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "ageRange" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "profileCompletedAt" TIMESTAMP(3);
