ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "commentsVisibleToFriends" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "visitedPlacesVisibleToFriends" BOOLEAN NOT NULL DEFAULT false;
